apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: microservices
data:
  # PostgreSQL Configuration
  POSTGRES_DB: db_parkin_users
  POSTGRES_USER: postgres
  DB_HOST: postgres-service
  DB_PORT: "5432"
  DB_NAME: db_parkin_users
  
  # Kong Configuration
  KONG_DATABASE: postgres
  KONG_PG_HOST: kong-postgres-service
  KONG_PG_USER: kong
  KONG_PG_DATABASE: kong
  KONG_ADMIN_LISTEN: "0.0.0.0:8001"
  
  # Microservices Configuration
  SERVER_PORT_ZONE: "8080"
  SERVER_PORT_CLIENTES: "8083"
  PORT_TICKETS: "4000"
  PORT_NOTIFICATIONS: "3001"
  NODE_ENV: production
  
  # Service URLs
  ZONE_SERVICE_URL: http://zone-core-service:8080
  PERSONA_SERVICE_URL: http://ms-clientes-service:8083
