apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: microservices
type: Opaque
stringData:
  # PostgreSQL Passwords
  POSTGRES_PASSWORD: angelo16
  DB_PASSWORD: angelo16
  DB_USERNAME: postgres
  
  # Kong Database Password
  KONG_PG_PASSWORD: kong
  
  # Database URLs
  SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-service:5432/db_parkin_users
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: angelo16
  DATABASE_URL: postgresql://postgres:angelo16@postgres-service:5432/db_parkin_users
